apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: lab-jobs
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';
    export const options = {
      vus: 50,
      duration: '10m',
    };
    export default function () {
      http.get('http://frontend.lab-app.svc.cluster.local/');
      sleep(0.1);
    }
